# Generated by Django 5.0.6 on 2024-05-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_uuid_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Admin"), (2, "Builder"), (3, "Trade"), (4, "Client")],
                default=4,
            ),
        ),
    ]
