# Generated by Django 5.0.6 on 2024-05-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_profile_picture_builder_client_trade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("builder", "Builder"),
                    ("trade", "Trade"),
                    ("client", "Client"),
                ],
                default="client",
                max_length=10,
            ),
        ),
    ]
