# Generated by Django 5.0.6 on 2024-06-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_builder_team_remove_builder_vbn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_no",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
