# Generated by Django 5.0.6 on 2024-06-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_postal_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_no",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
