# Generated by Django 5.0.6 on 2024-06-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_phone_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="services",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
