# Generated by Django 5.0.6 on 2024-07-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_trade_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_invited",
            field=models.BooleanField(default=False),
        ),
    ]
