# Generated by Django 5.0.6 on 2024-06-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("users", "0008_user_phone_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="address",
            field=models.CharField(blank=True, max_length=610, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="assignes",
            field=models.ManyToManyField(
                related_name="projects", to="users.builderemployee"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="city",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="developer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="logo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="no_of_homes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="postal_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="province",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("hold", "Hold"),
                    ("inactive", "Inactive"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="vbn",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
