# Generated by Django 5.0.6 on 2024-06-12 18:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_rename_assignes_project_assignees"),
        ("users", "0008_user_phone_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lot_no", models.CharField(blank=True, max_length=64, null=True)),
                ("stree_no", models.CharField(blank=True, max_length=64, null=True)),
                ("address", models.CharField(blank=True, max_length=256, null=True)),
                ("city", models.CharField(blank=True, max_length=64, null=True)),
                ("province", models.CharField(blank=True, max_length=64, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=32, null=True)),
                ("enrollment_no", models.IntegerField(blank=True, null=True)),
                ("warrantly_start_date", models.DateField()),
                ("home_type", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BluePrint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=64, null=True)),
                ("category", models.CharField(blank=True, max_length=64, null=True)),
                ("image", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "home",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.home",
                    ),
                ),
            ],
        ),
    ]
