# Generated by Django 5.0.6 on 2024-06-12 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_home_client_delete_blueprint"),
    ]

    operations = [
        migrations.CreateModel(
            name="BluePrint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=64, null=True)),
                ("category", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "home",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.home",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BluePrintImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "blue_print",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="projects.blueprint",
                    ),
                ),
            ],
        ),
    ]
