# Generated by Django 5.0.6 on 2024-06-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_blueprint_blueprintimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="home",
            old_name="stree_no",
            new_name="street_no",
        ),
        migrations.RenameField(
            model_name="home",
            old_name="warrantly_start_date",
            new_name="warranty_start_date",
        ),
    ]
