# Generated by Django 5.0.6 on 2024-06-12 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_rename_stree_no_home_street_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homes",
                to="projects.project",
            ),
        ),
    ]
