# Generated by Django 5.0.6 on 2024-06-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_alter_home_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="warranty_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
