# Generated by Django 5.0.6 on 2024-07-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_alter_home_enrollment_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="enrollment_no",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
