# Generated by Django 5.0.6 on 2024-08-02 05:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_home_owner_email_home_owner_name_home_owner_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="home",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
