# Generated by Django 5.0.6 on 2024-06-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deficiency",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="deficiency",
            name="status",
            field=models.CharField(
                choices=[
                    ("complete", "Complete"),
                    ("incomplete", "Incomplete"),
                    ("pending_approval", "Pending Approval"),
                ],
                default="incomplete",
                max_length=64,
            ),
        ),
    ]
