# Generated by Django 5.0.6 on 2024-06-29 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0002_deficiency_created_at_deficiency_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeficiencyReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "deficiency",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="inspections.deficiency",
                    ),
                ),
            ],
        ),
    ]
