# Generated by Django 5.0.6 on 2024-06-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0004_deficiency_is_reviewed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deficiencyreview",
            name="review",
        ),
        migrations.AddField(
            model_name="deficiencyreview",
            name="designate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deficiencyreview",
            name="home_owner",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
