# Generated by Django 5.0.6 on 2024-06-29 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0005_remove_deficiencyreview_review_and_more"),
        ("projects", "0014_alter_project_postal_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deficiency",
            name="home",
        ),
        migrations.RemoveField(
            model_name="deficiency",
            name="inspection",
        ),
        migrations.RemoveField(
            model_name="deficiency",
            name="project",
        ),
        migrations.CreateModel(
            name="HomeInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inspector_name", models.CharField(max_length=128)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projects.home"
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inspections.inspection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HomeInspectionReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "inspector_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("designate", models.BooleanField(default=False)),
                (
                    "home_inspection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="inspections.homeinspection",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DeficiencyReview",
        ),
    ]
