# Generated by Django 5.0.6 on 2024-06-29 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inspections",
            "0006_remove_deficiency_home_remove_deficiency_inspection_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="deficiency",
            name="home_inspection",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deficiencies",
                to="inspections.homeinspection",
            ),
        ),
    ]
