# Generated by Django 5.0.6 on 2024-06-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0008_alter_deficiency_home_inspection"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeinspection",
            name="is_reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
