# Generated by Django 5.0.6 on 2024-07-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0009_homeinspection_is_reviewed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homeinspection",
            name="inspector_name",
        ),
        migrations.RemoveField(
            model_name="homeinspectionreview",
            name="inspector_name",
        ),
        migrations.AddField(
            model_name="homeinspectionreview",
            name="inspector_signature_image",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="homeinspectionreview",
            name="owner_signature_image",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
