# Generated by Django 5.0.6 on 2024-07-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0011_deficiencyupdatelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeinspection",
            name="owner_visibility",
            field=models.BooleanField(default=False),
        ),
    ]
