# Generated by Django 5.0.6 on 2025-03-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0017_alter_homeinspection_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeinspection",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
