# Generated by Django 5.0.6 on 2025-04-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0018_homeinspection_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deficiency",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
