# Generated by Django 5.0.6 on 2025-05-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0019_alter_deficiency_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="deficiency",
            name="edit_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
